### ISSUE TITLE
1.20.4无法加载工业

### ISSUE THREAD

**Issue by theabab2333** [SlimefunGuguProject/LiteXpansion#43]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/LiteXpansion/issues)，且没有找到相同的问题

### 问题描述

使用的是https://github.com/SlimefunGuguProject/LiteXpansion/actions/runs/7758285983中xinzi构建的版本
同时构建站下载的版本也出现同样问题
错误原因看日志qwq

### 复现步骤

1.服务端核心为purpur1.20.4 2138
2.使用的工业版本为actions中下载的https://github.com/SlimefunGuguProject/LiteXpansion/actions/runs/7758285983
3.所用插件在底下sf版本里面都有

### 预期行为

因为想让xinzi为鸽子窝加上haiman科技(前置中需要工业) 但是xinzi说工业无法在1.20.4中被加载 我认为应该正常启动
于是测试1.20.1与1.20.4中工业是否被加载
结果是1.20.1成功加载 1.20.4却崩溃

### 服务器日志

https://paste.guizhanss.net/2CMM0

### 服务端软件

Purpur

### Minecraft 版本

1.20.4

### Slimefun版本

![image](https://github.com/SlimefunGuguProject/LiteXpansion/assets/102858947/62b8ca90-3391-49fb-818b-19d508c0b9cd)
截图里面qwq

### 插件版本

Build 31 (git 4f03e6b)

**Comment by DLucxoket** [comment]
遇到同样的问题，求解决

**Comment by theabab2333** [comment]
> 遇到同样的问题，求解决

好像是1.20.3开始水龙头端就把自定义发光附魔改了 然后工业报废
